### ISSUE TITLE
CV_bridge DIR error Install

### ISSUE THREAD

**Issue by Abdurrasith** [WHILL/gpu_stereo_image_proc#1]
I get this error when i try installing gpu_stereo_image_proc on my Jetson Xavier platform..

-- Could NOT find cv_bridge (missing: cv_bridge_DIR)
-- Could not find the required component 'cv_bridge'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "cv_bridge" with
  any of the following names:

    cv_bridgeConfig.cmake
    cv_bridge-config.cmake

  Add the installation prefix of "cv_bridge" to CMAKE_PREFIX_PATH or set
  "cv_bridge_DIR" to a directory containing one of the above files.  If
  "cv_bridge" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  gpu_stereo_image_proc/CMakeLists.txt:4 (find_package)

How Can I solve it? Thanks... I think CV_bridge has no support on ROS melodic in Ubuntu 18.04 especially ARM64 paltform

**Comment by seiya0412** [comment]
Hi, thank you for your report.
Have you installed cv-bridge on your Xavier?
I just logged in my Xavier and checked that cv-bridge package was available on L4T 32.2 (AARCH64 + Ubuntu 18.04).
Try the following command and feedback the result. 
```
sudo apt install ros-melodic-cv-bridge
```

Thx.

**Comment by seiya0412** [comment]
More easily, you can try
```
rosdep install -y gpu_stereo_image_proc --rosdistro=melodic
```
to install all the ROS packages on which gpu_stereo_image_proc depends.

**Comment by Abdurrasith** [comment]
> sudo apt install ros-melodic-cv-bridge

yes, i have been try to install with this script and getting an error

dpkg: error processing archive /var/cache/apt/archives/libopencv-dev_3.2.0+dfsg-4ubuntu0.1_arm64.deb (--unpack):
 trying to overwrite '/usr/bin/opencv_version', which is also in package libopencv 3.3.1
Selecting previously unselected package ros-melodic-cv-bridge.
Preparing to unpack .../ros-melodic-cv-bridge_1.13.0-0bionic.20191009.142329_arm64.deb ...
Unpacking ros-melodic-cv-bridge (1.13.0-0bionic.20191009.142329) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libopencv-dev_3.2.0+dfsg-4ubuntu0.1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Abdurrasith** [comment]
> to install all the ROS packages on which gpu_stereo_image_proc depends.

I trying another option with installing vision_OpenCV package for ROS too...
It's successfull to adding cv_bridge package, but the error change to imageproc.config

CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "image_proc" with
  any of the following names:

    image_procConfig.cmake
    image_proc-config.cmake

  Add the installation prefix of "image_proc" to CMAKE_PREFIX_PATH or set
  "image_proc_DIR" to a directory containing one of the above files.  If
  "image_proc" provides a separate development package or SDK, be sure it has
  been installed.

Can you told me the tutorial clearly to use your code? i need it for my study #thanks for the sharing

**Comment by seiya0412** [comment]
image_proc is another ROS package. http://wiki.ros.org/image_proc (ros-melodic-image-proc)
Try `rosdep install -y gpu_stereo_image_proc --rosdistro=melodic` instead of installing dependencies one-by-one.

If you want to run apt (or apt-get) by yourself for some reasons, here is the complete list of dependencies.
https://github.com/WHILL/gpu_stereo_image_proc/blob/cc9259f436ba5afca23c393002bc68bb3b03029d/package.xml#L19-L28

**Comment by seiya0412** [comment]
> Can you told me the tutorial clearly to use your code?

Simply speaking, gpu_stereo_image_proc is just a replacement (i.g. GPU implementation) of existing stereo_image_proc package. http://wiki.ros.org/stereo_image_proc?distro=melodic
Basic usage is completely identical with stereo_image_proc package.
Documentation of the package will help you.
For example, launching image proc nodes are quite simple:
- Launch your camera driver (you need to prepare them by your own), then
- Launch stereo_image_proc node (libsgm_stereo_image_proc.launch or vx_stereo_image_proc.launch).

If you want details of SGBM algorithm itself, visit [libSGM repository](https://github.com/fixstars/libSGM) or [NVIDIA VisionWorks Documentation](https://developer.nvidia.com/embedded/visionworks).

**Comment by Abdurrasith** [comment]
https://github.com/WHILL/gpu_stereo_image_proc/blob/cc9259f436ba5afca23c393002bc68bb3b03029d/package.xml#L19-L28

thanks a lot for the sharing
