### ISSUE TITLE
Missing image size conversion for vx-disparity 

### ISSUE THREAD

**Issue by JD-ETH** [WHILL/gpu_stereo_image_proc#2]
**Describe the bug**
Image size from vx-disparity is taken from the base class defaulted at (640 x 480), with no way of modifying them in either base or derived class. 

For rectified images at other image size the disparity image returns empty for vx. It doesn't show any error messages either as the copy into and from openvx image hides such error status.

**To Reproduce**
Run vx disparity computation from different image size.

**Expected behavior**
Should work. 
**Machine (please complete the following information):**
 - OS and version: Ubuntu 18.04 
 - ROS version  melodic 
 - Version or Commit melodic devel

**Additional context**
one workaround i did now is adding a image_size setter and getter in the `sgbm_processor` base class. When `imageCb` gets called in vx, it detects for image size mismatch, resize the image and reapply config.

**Comment by seiya0412** [comment]
Hi JD-ETH, thank you very much for your comment.
I will take a look.

**Comment by seiya0412** [comment]
Should be fixed by #5 .
