### ISSUE TITLE
Symbol Lookup Error for libsgm_stereo_image_proc

### ISSUE THREAD

**Issue by sanatmharolkar** [WHILL/gpu_stereo_image_proc#4]
I've build the package according the instructions. vx_stereo_image_proc runs properly. However, when I try to run libsgm_stereo_image_proc, I get the following error:

`/opt/ros/melodic/lib/nodelet/nodelet: symbol lookup error: /home/user/catkin_ws/devel/lib//liblibsgm_stereo_image_proc.so: undefined symbol: _ZNsgm13LibSGMWrapperC1EiiifbNS_8PathTypeEii`

This causes a failure to load nodelet /stereo/disparity and /stereo/point_cloud2

**Comment by seiya0412** [comment]
Looks like version mismatch between libSGM and gpu_stereo_image_proc.
I'll check it out. Thanks for your report.

**Comment by seiya0412** [comment]
@drfastolfe
Do you have local (i.e. built by your own) libSGM on your machine?
If so, can your update your local libSGM to latest (or at least 2.6.0)?
