### ISSUE TITLE
if my camera didn't have nodelet, how can i use this repo successfullly?

### ISSUE THREAD

**Issue by wanziwanziwanzi** [WHILL/gpu_stereo_image_proc#8]
my camera use python to get camera information, such as /stereo/left/image_raw, /stereo/left/info. But i don't know how to use nodelet to build python' node. So, if my camera didn't have nodelet, how can i use this repo successfullly?   thank you!

**Comment by seiya0412** [comment]
@wanziwanziwanzi  Camera node doesn't have to be a nodelet.
Simply run your camera node and then launch gpu_stereo_image_proc's nodelet as follows.
>  such as /stereo/left/image_raw, /stereo/left/info



```
# Launch your nodelet manager
rosrun nodelet nodelet manager __name:=manager # Note that manager must be located in global namespace

# Launch image processing nodelets
roslaunch gpu_stereo_image_proc comparison.launch manager:=/manager __ns:=/stereo # Don't forget '/' before manager's name.
```

>  such as /stereo/left/image_raw, /stereo/left/info

Note that your stereo camera's namespace is `/stereo`.
So provide namespace option to launch by `__ns:=/stereo` phrase.

Feel free to let me know if it doesn't work.

**Comment by wanziwanziwanzi** [comment]
thank you for you answer. 
(1) first, i run my camera:  
` roslaunch arducam_stereo_camera arducam_stereo_camera.launch`
i get camera info:  
`/arducam/left/camera_info`
`/arducam/left/image_raw`
`/arducam/right/camera_info`
`/arducam/right/image_raw`
`/rosout `
`/rosout_agg`

(2) then i run nodelet manager:
`rosrun nodelet nodelet manager __name:=my_manager`

(3) i run `roslaunch gpu_stereo_image_proc libsgm_stereo_image_proc.launch manager:=/my_manager __ns:=/arducam`
i can get:
/arducam/disparity
/arducam/disparity/parameter_descriptions
/arducam/disparity/parameter_updates
/arducam/left/camera_info
/arducam/left/debayer/parameter_descriptions
/arducam/left/debayer/parameter_updates
/arducam/left/image_color
/arducam/left/image_color/compressed
/arducam/left/image_color/compressed/parameter_descriptions
/arducam/left/image_color/compressed/parameter_updates
/arducam/left/image_color/compressedDepth
/arducam/left/image_color/compressedDepth/parameter_descriptions
/arducam/left/image_color/compressedDepth/parameter_updates
/arducam/left/image_color/theora
/arducam/left/image_color/theora/parameter_descriptions
/arducam/left/image_color/theora/parameter_updates
/arducam/left/image_mono
/arducam/left/image_mono/compressed
/arducam/left/image_mono/compressed/parameter_descriptions
/arducam/left/image_mono/compressed/parameter_updates
/arducam/left/image_mono/compressedDepth
/arducam/left/image_mono/compressedDepth/parameter_descriptions
/arducam/left/image_mono/compressedDepth/parameter_updates
/arducam/left/image_mono/theora
/arducam/left/image_mono/theora/parameter_descriptions
/arducam/left/image_mono/theora/parameter_updates
/arducam/left/image_raw
/arducam/left/image_rect
/arducam/left/image_rect/compressed
/arducam/left/image_rect/compressed/parameter_descriptions
/arducam/left/image_rect/compressed/parameter_updates
/arducam/left/image_rect/compressedDepth
/arducam/left/image_rect/compressedDepth/parameter_descriptions
/arducam/left/image_rect/compressedDepth/parameter_updates
/arducam/left/image_rect/theora
/arducam/left/image_rect/theora/parameter_descriptions
/arducam/left/image_rect/theora/parameter_updates
/arducam/left/image_rect_color
/arducam/left/image_rect_color/compressed
/arducam/left/image_rect_color/compressed/parameter_descriptions
/arducam/left/image_rect_color/compressed/parameter_updates
/arducam/left/image_rect_color/compressedDepth
/arducam/left/image_rect_color/compressedDepth/parameter_descriptions
/arducam/left/image_rect_color/compressedDepth/parameter_updates
/arducam/left/image_rect_color/theora
/arducam/left/image_rect_color/theora/parameter_descriptions
/arducam/left/image_rect_color/theora/parameter_updates
/arducam/left/rectify_color/parameter_descriptions
/arducam/left/rectify_color/parameter_updates
/arducam/left/rectify_mono/parameter_descriptions
/arducam/left/rectify_mono/parameter_updates
/arducam/points2
/arducam/right/camera_info
/arducam/right/debayer/parameter_descriptions
/arducam/right/debayer/parameter_updates
/arducam/right/image_color
/arducam/right/image_color/compressed
/arducam/right/image_color/compressed/parameter_descriptions
/arducam/right/image_color/compressed/parameter_updates
/arducam/right/image_color/compressedDepth
/arducam/right/image_color/compressedDepth/parameter_descriptions
/arducam/right/image_color/compressedDepth/parameter_updates
/arducam/right/image_color/theora
/arducam/right/image_color/theora/parameter_descriptions
/arducam/right/image_color/theora/parameter_updates
/arducam/right/image_mono
/arducam/right/image_mono/compressed
/arducam/right/image_mono/compressed/parameter_descriptions
/arducam/right/image_mono/compressed/parameter_updates
/arducam/right/image_mono/compressedDepth
/arducam/right/image_mono/compressedDepth/parameter_descriptions
/arducam/right/image_mono/compressedDepth/parameter_updates
/arducam/right/image_mono/theora
/arducam/right/image_mono/theora/parameter_descriptions
/arducam/right/image_mono/theora/parameter_updates
/arducam/right/image_raw
/arducam/right/image_rect
/arducam/right/image_rect/compressed
/arducam/right/image_rect/compressed/parameter_descriptions
/arducam/right/image_rect/compressed/parameter_updates
/arducam/right/image_rect/compressedDepth
/arducam/right/image_rect/compressedDepth/parameter_descriptions
/arducam/right/image_rect/compressedDepth/parameter_updates
/arducam/right/image_rect/theora
/arducam/right/image_rect/theora/parameter_descriptions
/arducam/right/image_rect/theora/parameter_updates
/arducam/right/image_rect_color
/arducam/right/image_rect_color/compressed
/arducam/right/image_rect_color/compressed/parameter_descriptions
/arducam/right/image_rect_color/compressed/parameter_updates
/arducam/right/image_rect_color/compressedDepth
/arducam/right/image_rect_color/compressedDepth/parameter_descriptions
/arducam/right/image_rect_color/compressedDepth/parameter_updates
/arducam/right/image_rect_color/theora
/arducam/right/image_rect_color/theora/parameter_descriptions
/arducam/right/image_rect_color/theora/parameter_updates
/arducam/right/rectify_color/parameter_descriptions
/arducam/right/rectify_color/parameter_updates
/arducam/right/rectify_mono/parameter_descriptions
/arducam/right/rectify_mono/parameter_updates
/rosout
/rosout_agg
/tf_static

(4) i run `rosrun rviz rviz` for visualization:
but how can i set  fixed frame to get the correct pcl? or i didn't get the whole node?
![2021-05-27 16-14-34屏幕截图](https://user-images.githubusercontent.com/33322553/119791011-01c07b00-bf07-11eb-998d-5d2814379222.png)

(5)later, i run `roslaunch gpu_stereo_image_proc comparison.launch manager:=/my_manager __ns:=/arducam`  to instead of  `roslaunch gpu_stereo_image_proc libsgm_stereo_image_proc.launch manager:=/my_manager __ns:=/arducam `

i can get:
/arducam/libsgm_disparity
/arducam/libsgm_disparity/parameter_descriptions
/arducam/libsgm_disparity/parameter_updates
/arducam/libsgm_points2
/arducam/vx_disparity
/arducam/vx_disparity/parameter_descriptions
/arducam/vx_disparity/parameter_updates
/arducam/vx_points2

but what can i do to set rviz for display those results, thank you!
my fixed frame can option:  cameraLeft,map  or tmp.
![2021-05-27 17-05-54屏幕截图](https://user-images.githubusercontent.com/33322553/119798892-22d89a00-bf0e-11eb-8d54-0a35b5a5e291.png)

**Comment by seiya0412** [comment]
@wanziwanziwanzi 
```
/arducam/points2
```
This is the final output (pointcloud) of the libsgm_stereo_image_proc.launch, and

```
/arducam/libsgm_points2
/arducam/vx_points2
```
they are  the final outputs of the comparison.launch.

So it looks like every required nodes are up and running.

Please try to `rostopic echo` and `rostopic hz` to see if these topics are published at your desired rate.

> how can i set fixed frame
All cameraLeft, tmp and map should work. Can you check tf tree by `rqt_tf_tree`?

https://github.com/WHILL/gpu_stereo_image_proc/blob/b9284bd0fa1b7d325bb6333f78373bb0cee65a9a/launch/comparison.launch#L78-L79

**Comment by wanziwanziwanzi** [comment]
(1) first,  i run `rostopic echo` and `rostopic hz`,  can get data from   `/arducam/points2`:
![2021-05-28 09-07-28屏幕截图(复件)](https://user-images.githubusercontent.com/33322553/119915531-4abf1080-bf95-11eb-81ea-3109cf8f3b44.png)

(2) i check tf tree by `rqt_tf_tree`:
`  <node pkg="tf2_ros" type="static_transform_publisher" name="map_to_tmp" args="0 0 0 0 1.57079632679 0 map tmp" ns="stereo" />`
` <node pkg="tf2_ros" type="static_transform_publisher" name="tmp_to_cameraLeft" args="0 0 0 -1.57079632679 0 0 tmp cameraLeft" ns="stereo"/>`

`ns="stereo"`  and `ns="arducam"`,  PCL will not appear in both cases，but i can get other image topics：
![2021-05-28 09-07-28屏幕截图](https://user-images.githubusercontent.com/33322553/119915905-1009a800-bf96-11eb-89ba-38448f4a318d.png)

thank for you reply!

**Comment by seiya0412** [comment]
@wanziwanziwanzi 
It seems like `/arducam/points2` is filled with valid data and is published at approx. 5Hz. So the node is running and working.
Can you give me the result of `rostopic echo /arducam/points2/header` please?
The header of the topic must have `frame_id`.

**Comment by wanziwanziwanzi** [comment]
sorry, i get a new error:
`[ERROR] [1622167362.315156835]: Failed to load nodelet [/arducam/left/rectify_mono] of type [image_proc/rectify] even after refreshing the cache: Failed to load library /home/wong/ROS_WORKSPACE/CAM/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_calib3d.so.3.4: cannot open shared object file: No such file or directory)
`

i don't know what happened, i  build `fix/variable_image_size` branch,  but when i run `rosrun nodelet nodelet manager __name:=my_manager` , error happened. then, i rebuild `melodic master` branch, it also happened.

**Comment by seiya0412** [comment]
@wanziwanziwanzi 
It's environment-dependent and I don't have a perfect solution for you.
I would recommend to clean up the environment ( `catkin_make clean` if you use `catkin_make`, or `catkin clean` if you use catkin build tools) and rebuild the project.

Note that `fix/variable_image_size` branch was already merged into `melodic-devel` and you don't have to use it. Use `melodic-devel` branch only.

**Comment by wanziwanziwanzi** [comment]
the result of ` rostopic echo /arducam/points2/header` is like this:
![2021-05-28 11-20-46屏幕截图](https://user-images.githubusercontent.com/33322553/119924916-08063400-bfa7-11eb-9244-6ebce41c9a87.png)

**Comment by seiya0412** [comment]
Okay, so your /arducam/point2 is published with "cam0" coordinate frame.
Does your RVIZ have "cam0" for Global Option -> Fixed Frame?
It is the frame id you should select.

**Comment by wanziwanziwanzi** [comment]
i don't have "cam0" Frame for optional, what can i do to get the "cam0" frame or change "cam0" with other frame for visualization. thank you!

**Comment by wanziwanziwanzi** [comment]
thanks for you answer, i change frame to "cam0", it can work well.

**Comment by seiya0412** [comment]
Great! Thank you for the comment.
